from django.urls import path, include
from .import views
from django.conf import settings
urlpatterns = [

 
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('ureg/', views.user_reg, name='user_reg'),
    path('', views.Student_Home, name='Student_Home'),
    path('Lib_Home', views.Lib_Home, name='Lib_Home'),
    path('about/', views.about, name='about'),
    path('logout/', views.logout, name='logout'),
    path('changepassword/', views.changepassword, name='changepassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    path('Service/', views.Service, name='Service'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('Hostel_home/', views.Hostel_home, name='Hostel_home'),
    path('Outpass/', views.Outpass, name='Outpass'),
    path('outpass_history/',views.outpass_history,name='outpass_history'),
    path('outpassedit/<int:id>/',views.outpassedit,name='outpassedit'),
    path('outpassupdate/<int:id>/',views.outpassupdate,name='outpassupdate'),
    path('deleteoutpass/<int:id>/',views.deleteoutpass,name='deleteoutpass'),
    # path('send_outpassinfomail/', views.send_outpassinfomail, name='send_outpassinfomail'), 
    path('profile/', views.profile, name='profile'),
    path('profile/update',views.profile_update,name='profile_update'),
    path('Library_home/', views.Library_home, name='Library_home'),
    path('Viewbookindex/', views.Viewbookindex, name='Viewbookindex'),
    path('onebook/<str:id>/',views.onebook,name='onebook'),
    path('Catagory_Books/<str:id>/',views.Catagory_Books,name='Catagory_Books'),
    path('searchbar',views.searchbar,name='searchbar'),
    path('form/', views.uploadForm, name='form'),
    path('files/', views.files, name='files'),
    path('upload/', views.uploadFile, name='upload'),
    path('deletepdf/<int:id>/',views.deletepdf,name='deletepdf'),
    path('issuebooklib/<int:id>/', views.issuebooklib, name='issuebooklib'),
    path('student_issued_books/', views.student_issued_books, name='student_issued_books'),
    path('return_book_lib/<int:id>/', views.return_book_lib, name='return_book_lib'),
    path('mybooks/', views.mybooks, name="mybooks"), 
    path('Wardenhome/', views.Wardenhome, name='Wardenhome'),
    path('WardenOutpassView/',views.WardenOutpassView,name='WardenOutpassView'),
    path('outpassapproved/<str:leave_id>',views.outpassapproved,name='outpassapproved'),
    path('outpassdisapprove/<str:leave_id>', views.outpassdisapprove,name="outpassdisapprove"),
    path('WardenDue/', views.WardenDue, name='WardenDue'),
    path('calculate-mess-fee/',views.calculate_mess_fee, name='calculate_mess_fee'),
    path('Student_complaint/', views.Student_complaint, name='Student_complaint'),
    path('Student_complaint_save', views.Student_complaint_save, name="Student_complaint_save"),
    path('WardenComplaintView', views.WardenComplaintView, name="WardenComplaintView"),
    path('student_complaint_message_replied/', views.student_complaint_message_replied, name="student_complaint_message_replied"),
    
    path('WardenMess/', views.WardenMess, name='WardenMess'),
    # path('warden_add_due/', views.warden_add_due, name='warden_add_due'),
    # path('warden_remove_due/', views.warden_remove_due, name='warden_remove_due'),
    # path('send-sms/', views.send_sms, name='send_sms'),
    path('Addroom', views.Addroom, name='Addroom'),
    path('table/',views.table,name='table'),
    path('addroomtable/<int:id>/',views.addroomtable,name='addroomtable'),
    path('productedit/<int:id>/',views.productedit,name='productedit'),
    path('productupdate/',views.productupdate,name='productupdate'),
    path('deleteproduct/<int:id>/',views.deleteproduct,name='deleteproduct'),
    path('Room_view',views.Room_view,name='Room_view'),
    path('RoomDetails/<int:id>/',views.RoomDetails,name='RoomDetails'),
    path('paymentdone',views.payment_done,name='paymentdone'),
    path('showbill',views.showbill,name='showbill'),
    # path('Warden_AttendenceView',views.Warden_AttendenceView,name='Warden_AttendenceView'),
    # path('ajax/', views.ajax, name= 'ajax'),
    # path('scan/',views.scan,name='scan'),
    # path('details/', views.details, name= 'details'),
    # path('reset/',views.reset,name='reset'),
    # path('clear_history/',views.clear_history,name='clear_history'),
    path('pdf/<int:id>/', views.get,name='pdf'),
    path('WardenViewPaymentDetails/',views.WardenViewPaymentDetails,name='WardenViewPaymentDetails'),
    path('order_detailslog/',views.order_detailslog,name='order_detailslog'),
    path('Librarianhome', views.Librarianhome, name="Librarianhome"),
    path('LibrarianAddBook', views.LibrarianAddBook, name='LibrarianAddBook'),
    path('booktable', views.booktable, name='booktable'),
    path('addbooktable/<int:id>/',views.addbooktable,name='addbooktable'),
    path('bookedit/<int:id>/',views.bookedit,name='bookedit'),
    path('bookupdate/<int:id>/',views.bookupdate,name='bookupdate'),
    path('deletebook/<int:id>/',views.deletebook,name='deletebook'),
    path('Student_complaint/', views.Student_complaint, name='Student_complaint'),
    path('Student_complaint_save', views.Student_complaint_save, name="Student_complaint_save"),
    path('WardenComplaintView', views.WardenComplaintView, name="WardenComplaintView"),
    path('student_complaint_message_replied/', views.student_complaint_message_replied, name="student_complaint_message_replied"),
    


    ###########################################################################################################################
    path('StudentBookScomplaint/', views.StudentBookScomplaint, name='StudentBookScomplaint'),
    path('StudentBookScomplaint_save', views.StudentBookScomplaint_save, name="StudentBookScomplaint_save"),
    path('LibrarianComplaintView', views.LibrarianComplaintView, name="LibrarianComplaintView"),
    path('student_bookcomplaint_message_replied/', views.student_bookcomplaint_message_replied, name="student_bookcomplaint_message_replied"),
    path('Librarian_issuedbooklist', views.Librarian_issuedbooklist, name="Librarian_issuedbooklist"),
    path('order_detailslog/',views.order_detailslog,name='order_detailslog'),
    path('payment_success/<int:id>/', views.payment_success, name='payment_success'),
    # path('messfee_studentview/', views.messfee_studentview, name='messfee_studentview'),

    #########################################################################
    path('generate_mess_fee/', views.generate_mess_fee, name='generate_mess_fee'),
    path('paymentdone/', views.paymentdone, name='paymentdone'),
    path('messfee_studentview/', views.messfee_studentview, name='messfee_studentview'),
    # path('messfee_studentview/', messfee_studentview, name='messfee_studentview'),
    # path('mess_fee_details/', views.mess_fee_details, name='mess_fee_details'),
    # path('recommendations/', views.book_recommendations, name='recommendations'),
]
