# Generated by Django 4.1.2 on 2023-02-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0002_tbl_outpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_outpass',
            name='parents_email',
            field=models.EmailField(default=0, max_length=100),
        ),
    ]
