# Generated by Django 4.1.2 on 2023-02-25 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0004_alter_tbl_outpass_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_outpass',
            old_name='o_id',
            new_name='id',
        ),
    ]
