# Generated by Django 4.1.2 on 2023-02-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0005_rename_o_id_tbl_outpass_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_outpass',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
