# Generated by Django 4.1.2 on 2023-02-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0009_addmessfee_feestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmessfee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
