# Generated by Django 4.1.2 on 2023-02-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0010_alter_addmessfee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmessfee',
            name='date_paid',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='addmessfee',
            name='feestatus',
            field=models.BooleanField(default=False),
        ),
    ]
