# Generated by Django 4.1.2 on 2023-02-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0011_addmessfee_date_paid_alter_addmessfee_feestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addmessfee',
        ),
    ]
