# Generated by Django 4.1.2 on 2023-02-26 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0013_addmessfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmessfee',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='hostelcomplaints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateField(auto_now=True)),
                ('complaint', models.CharField(max_length=100)),
                ('complaint_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
