# Generated by Django 4.1.2 on 2023-02-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0013_addmessfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmessfee',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
