# Generated by Django 4.1.2 on 2023-02-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0014_alter_addmessfee_amount_hostelcomplaints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hostelcomplaints',
        ),
    ]
