# Generated by Django 4.1.2 on 2023-02-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0014_alter_addmessfee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmessfee',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
