# Generated by Django 4.1.2 on 2023-02-27 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0015_delete_hostelcomplaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.TextField()),
                ('complaint_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
