# Generated by Django 4.1.2 on 2023-03-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0018_remove_tbl_outpass_action_account_img_and_more'),
    ]

    operations = [
      
    ]
