# Generated by Django 4.1.2 on 2023-03-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0018_remove_tbl_outpass_action_account_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmessfee',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
