# Generated by Django 4.1.2 on 2023-03-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0018_remove_tbl_outpass_action_account_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_outpass',
            name='action',
        ),
    ]
