# Generated by Django 4.1.2 on 2023-03-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0019_remove_tbl_outpass_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmessfee',
            name='feestatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complaintstudent',
            name='complaint',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='complaintstudent',
            name='complaint_reply',
            field=models.TextField(max_length=500),
        ),
    ]
