# Generated by Django 4.1.2 on 2023-03-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0020_alter_addmessfee_feestatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmessfee',
            name='feestatus',
            field=models.BooleanField(default=False),
        ),
    ]
