# Generated by Django 4.1.2 on 2023-03-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0022_fees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fees',
        ),
    ]
