# Generated by Django 4.1.2 on 2023-03-07 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0023_delete_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('mobno', models.BigIntegerField(default=0)),
                ('sem', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth'), ('Seventh', 'Seventh'), ('Eighth', 'Eighth'), ('None', 'None')], max_length=100)),
                ('ldate', models.DateTimeField()),
                ('idate', models.DateTimeField()),
                ('purpose', models.CharField(max_length=100)),
                ('dest', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('parents_email', models.EmailField(default=0, max_length=100)),
                ('parents_contact', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
       
    ]
