# Generated by Django 4.1.2 on 2023-03-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0024_leave_delete_tbl_outpass'),
    ]

