# Generated by Django 4.1.2 on 2023-03-09 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0026_course_hostel_room_warden_delete_tbl_outpass'),
    ]

    operations = [
        
    ]
