# Generated by Django 4.1.2 on 2023-03-09 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0027_delete_tbl_outpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('N', 'None'), ('M', 'Male'), ('F', 'Female')], default='N', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='no_dues',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycardapp.room'),
        ),
        migrations.AddField(
            model_name='account',
            name='room_allotted',
            field=models.BooleanField(default=False),
        ),
        
    ]
