# Generated by Django 4.1.2 on 2023-03-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0029_leaves_delete_tbl_outpass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='id',
        ),
        
    ]
