# Generated by Django 4.1.2 on 2023-03-16 09:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0030_rename_book_id_book_id_delete_tbl_outpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('phone', models.CharField(max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='e-mail')),
                ('city', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('checkIn', models.DateField()),
                ('checkOut', models.DateField()),
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_alloted', models.BooleanField(default=False)),
                ('accept', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mycardapp.guest')),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mycardapp.room')),
            ],
            options={
                'verbose_name_plural': 'Reservation',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('max_persons', models.IntegerField(default=2)),
                ('room_type', models.CharField(choices=[('S', 'Single Occupancy'), ('D', 'Double Occupancy')], default=None, max_length=1)),
                ('price', models.IntegerField(default=500)),
            ],
        ),
        
    ]
