# Generated by Django 4.1.2 on 2023-03-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0031_guest_reservation_rooms_delete_tbl_outpass'),
    ]

    operations = [
       
        migrations.DeleteModel(
            name='Leaves',
        ),
       
    ]
