# Generated by Django 4.1.2 on 2023-03-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0032_remove_tbl_outpass_user_delete_leaves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warden',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='user',
        ),
        migrations.DeleteModel(
            name='Warden',
        ),
    ]
