# Generated by Django 4.1.2 on 2023-03-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0033_remove_warden_hostel_remove_warden_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
       
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        
    ]
