# Generated by Django 4.1.2 on 2023-03-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0034_remove_guest_user_remove_reservation_guest_and_more'),
    ]

    operations = [
        
    ]
