# Generated by Django 4.1.2 on 2023-03-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0035_delete_tbl_outpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(default='', upload_to='room_image/'),
        ),
       
    ]
