# Generated by Django 4.1.2 on 2023-03-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0036_room_available_room_description_room_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
       
    ]
