# Generated by Django 4.1.2 on 2023-03-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0037_remove_document_category_remove_tbl_outpass_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='no',
        ),
        migrations.RemoveField(
            model_name='room',
            name='repair',
        ),
        migrations.RemoveField(
            model_name='room',
            name='vacant',
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
