# Generated by Django 4.1.2 on 2023-03-22 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0039_encryptedfile_delete_tbl_outpass'),
    ]

    operations = [
        
        migrations.DeleteModel(
            name='EncryptedFile',
        ),
        
    ]
