# Generated by Django 4.1.2 on 2023-03-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0040_remove_tbl_outpass_user_delete_encryptedfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/encrypted/')),
                ('key', models.BinaryField()),
            ],
        ),
        
    ]
