# Generated by Django 4.1.2 on 2023-03-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0046_orderplaced_delete_tbl_outpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='present',
            field=models.BooleanField(default=False),
        ),
    
    ]
