# Generated by Django 4.1.2 on 2023-03-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0047_account_present_delete_tbl_outpass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='img',
            new_name='image',
        ),
       
    ]
