# Generated by Django 4.1.2 on 2023-03-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0048_rename_img_account_image_delete_tbl_outpass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='room',
        ),
        
    ]
