# Generated by Django 4.1.2 on 2023-03-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0051_orderplaced_quantity_delete_tbl_outpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mycardapp.room'),
        ),
        
    ]
