# Generated by Django 4.1.2 on 2023-03-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0053_complaintbookstudent_delete_tbl_outpass'),
    ]

    operations = [
        
        migrations.DeleteModel(
            name='ComplaintBookStudent',
        ),
        
    ]
