# Generated by Django 4.1.2 on 2023-03-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0058_remove_issuedbook_enrollment_remove_issuedbook_isbn_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssuedBook',
        ),
        
    ]
