# Generated by Django 4.1.2 on 2023-03-30 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mycardapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0059_delete_issuedbook_delete_tbl_outpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_BookIssue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_issue', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(default=mycardapp.models.get_expiry)),
                ('issuedstatus', models.BooleanField(default=False)),
                ('fine', models.BigIntegerField(null=True)),
                ('payment', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('None', 'None')], default='Unpaid', max_length=40)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycardapp.book')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycardapp.category_book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
       
    ]
