# Generated by Django 4.1.2 on 2023-03-31 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0060_tbl_bookissue_delete_tbl_outpass'),
    ]

    operations = [
        
    ]
