# Generated by Django 4.1.2 on 2023-04-07 14:53

from django.db import migrations, models
import mycardapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0064_alter_tbl_bookissue_expiry_date_delete_tbl_outpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='choice',
            field=models.CharField(choices=[('N', 'None'), ('D', 'Day scholar'), ('H', 'Hosteler')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_bookissue',
            name='expiry_date',
            field=models.DateField(default=mycardapp.models.get_expiry),
        ),
    ]
