# Generated by Django 4.1.2 on 2023-04-07 15:08

from django.db import migrations, models
import mycardapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0065_account_choice_alter_tbl_bookissue_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='image',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='tbl_bookissue',
            name='expiry_date',
            field=models.DateField(default=mycardapp.models.get_expiry),
        ),
       
    ]
