# Generated by Django 4.1.2 on 2023-04-08 09:34

from django.db import migrations, models
import mycardapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0067_alter_tbl_bookissue_expiry_date_delete_tbl_outpass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_bookissues',
            old_name='issue_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='tbl_bookissue',
            name='expiry_date',
            field=models.DateField(default=mycardapp.models.get_expiry),
        ),
        
    ]
