# Generated by Django 4.1.2 on 2023-04-10 17:25

from django.db import migrations, models
import mycardapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0068_rename_issue_id_tbl_bookissues_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_bookissues',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_bookissue',
            name='expiry_date',
            field=models.DateField(default=mycardapp.models.get_expiry),
        ),
    ]
