# Generated by Django 4.1.2 on 2023-04-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0069_tbl_bookissues_payment_id_and_more'),
    ]

    operations = [
       
        migrations.DeleteModel(
            name='tbl_BookIssue',
        ),
    ]
