# Generated by Django 4.1.2 on 2023-04-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0070_remove_tbl_outpass_user_delete_tbl_bookissue_and_more'),
    ]

    operations = [
        
        migrations.DeleteModel(
            name='addmessfee',
        ),
        
    ]
