# Generated by Django 4.1.2 on 2023-04-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0073_messfees_delete_tbl_outpass'),
    ]

    operations = [
        
        migrations.DeleteModel(
            name='MessFees',
        ),
        
    ]
