# Generated by Django 4.1.2 on 2023-04-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0074_remove_tbl_outpass_user_delete_messfees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessFees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('None', 'None')], default='Unpaid', max_length=40)),
                ('payment_date', models.DateField(null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('leaves', models.ManyToManyField(to='mycardapp.leave')),
            ],
        ),
        
    ]
