# Generated by Django 4.1.2 on 2023-04-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0076_messfees_user_delete_tbl_outpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfees',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
