# Generated by Django 4.1.2 on 2023-05-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0079_searchhistory_delete_tbl_outpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfees',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='messfees',
            unique_together={('user', 'month', 'year')},
        ),
        
    ]
