# Generated by Django 4.1.2 on 2023-05-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0080_alter_messfees_amount_alter_messfees_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfees',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='messfees',
            name='payment',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('None', 'None')], default='Unpaid', max_length=6),
        ),
        
    ]
