# Generated by Django 4.1.2 on 2023-05-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0081_alter_messfees_amount_alter_messfees_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='librarian',
        ),
        
    ]
