# Generated by Django 4.1.2 on 2023-05-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0082_delete_librarian_delete_tbl_outpass'),
    ]

    operations = [
        
        migrations.DeleteModel(
            name='MessFee',
        ),
        
    ]
