# Generated by Django 4.1.2 on 2023-05-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0083_remove_tbl_outpass_user_delete_messfee_and_more'),
    ]

    operations = [
        
    ]
