# Generated by Django 4.1.2 on 2023-05-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0084_delete_tbl_outpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mess_fee_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
