# Generated by Django 4.1.2 on 2023-05-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0085_account_mess_fee_rate_delete_tbl_outpass'),
    ]

    operations = [
        
    ]
