# Generated by Django 4.1.2 on 2023-05-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycardapp', '0087_account_profile_updated_delete_tbl_outpass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile_updated',
        ),
    ]
